import Head from 'next/head'
import {HomePage} from '../src/components/home/home-page'


const Home = ({data}:any) => {
  return (
    <div>
      <Head>
        <title>Keyu Ye</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/IMG_3535.JPG" />
      </Head>
      <HomePage data={data}/>
    </div>
  );
}

export default Home;


export async function getStaticProps() {
  const {events_categories}= await import ('../data/data.json');

  return {
    props: {
            data: events_categories,
        }, 
    };
}
